# -*- coding: utf-8 -*-
"""SAW_VNA_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fctCPAsTGjcAz8DiVThXFreWykWIuMv
"""

!pip install scikit-rf
import skrf

import skrf as rf
import matplotlib.pyplot as plt


# Load the S2P file
# Replace 'your_file.s2p' with the actual path to your S2P file
file_path = 'gfdgsgf.s2p'  # Example: 'C:/data/measurement.s2p'
ntwk = rf.Network(file_path)

# Create a figure with subplots
fig = plt.figure(figsize=(12, 8))

# Plot all S-parameters in dB
plt.subplot(2, 1, 1)  # 2 rows, 1 column, first plot
#ntwk.plot_s_db(m=0, n=0, label='S11', linewidth=2)
ntwk.plot_s_db(m=1, n=0, label='S21', linewidth=2)
ntwk.plot_s_db(m=0, n=1, label='S12', linewidth=2)
#ntwk.plot_s_db(m=1, n=1, label='S22', linewidth=2)
plt.title(f'S-Parameters of {ntwk.name or "Network"}')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Magnitude (dB)')
plt.grid(True)
plt.legend()

# Plot phase information
plt.subplot(2, 1, 2)  # 2 rows, 1 column, second plot
#ntwk.plot_s_deg(m=0, n=0, label='S11 Phase', linewidth=2)
ntwk.plot_s_deg(m=1, n=0, label='S21 Phase', linewidth=2)
ntwk.plot_s_deg(m=0, n=1, label='S12 Phase', linewidth=2)
#ntwk.plot_s_deg(m=1, n=1, label='S22 Phase', linewidth=2)
plt.xlabel('Frequency (GHz)')
plt.ylabel('Phase (degrees)')
plt.grid(True)
plt.legend()

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the plots
plt.show()

# Print some information about the network
print("Network Summary:")
print(f"Name: {ntwk.name}")
print(f"Frequency range: {ntwk.f[0]/1e9:.2f} - {ntwk.f[-1]/1e9:.2f} GHz")
print(f"Number of points: {ntwk.f.size}")
print(f"Average S11: {ntwk.s_db[:,0,0].mean():.2f} dB")
print(f"Average S21: {ntwk.s_db[:,1,0].mean():.2f} dB")


# Plot S11 in dB
plt.figure(figsize=(10, 6))
ntwk.plot_s_db(m=0, n=0, label='S11', linewidth=2)
plt.title(f'S11 of {ntwk.name or "Network"}')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Magnitude (dB)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Plot S22 in dB
plt.figure(figsize=(10, 6))
ntwk.plot_s_db(m=1, n=1, label='S22', linewidth=2)
plt.title(f'S22 of {ntwk.name or "Network"}')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Magnitude (dB)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np

### Time Delay Calculation (Group Delay)
freq = ntwk.f  # Frequency points
phase_s21 = np.unwrap(np.angle(ntwk.s[:,1,0]))  # Unwrapped phase of S21
group_delay = -np.gradient(phase_s21, freq) / (2 * np.pi)  # Time delay calculation

plt.figure(figsize=(10, 6))
plt.plot(freq / 1e9, group_delay * 1e9, linewidth=2, label='Group Delay (S21)')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Group Delay (ns)')
plt.title(f'Group Delay of {ntwk.name or "Network"}')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

### Time-Domain Response via Inverse Fourier Transform (IFT)
s21_freq = ntwk.s[:,1,0]  # S21 in frequency domain
time_response = np.fft.ifft(s21_freq)  # Inverse FFT to get time-domain impulse response
time_axis = np.fft.fftfreq(len(freq), d=(freq[1] - freq[0]))  # Time axis

plt.figure(figsize=(10, 6))
plt.plot(time_axis * 1e9, np.abs(time_response), linewidth=2, label='IFT of S21')
plt.xlim(0, 100)  # Set y-axis limit to 0-100 ns
plt.xlabel('Time (ns)')
plt.ylabel('Magnitude')
plt.title(f'Time-Domain Response of {ntwk.name or "Network"}')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

### Fourier Transform (FT) of S21
s21_time = np.fft.fft(time_response)  # Forward FFT
freq_axis = np.fft.fftfreq(len(time_response), d=(time_axis[1] - time_axis[0]))  # Frequency axis

plt.figure(figsize=(10, 6))
plt.plot(freq_axis / 1e9, np.abs(s21_time), linewidth=2, label='Fourier Transform of S21')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Magnitude')
plt.title(f'Frequency Spectrum of {ntwk.name or "Network"}')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()




import numpy as np
import skrf as rf
import matplotlib.pyplot as plt

# Load the S2P file
file_path = 'gfdgsgf.s2p'  # Replace with actual file path
ntwk = rf.Network(file_path)

# Create a figure with subplots
fig = plt.figure(figsize=(12, 8))

# Plot all S-parameters in dB
plt.subplot(2, 1, 1)
ntwk.plot_s_db(m=1, n=0, label='S21', linewidth=2)
ntwk.plot_s_db(m=0, n=1, label='S12', linewidth=2)
plt.title(f'S-Parameters of {ntwk.name or "Network"}')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Magnitude (dB)')
plt.grid(True)
plt.legend()

# Plot phase information
plt.subplot(2, 1, 2)
ntwk.plot_s_deg(m=1, n=0, label='S21 Phase', linewidth=2)
ntwk.plot_s_deg(m=0, n=1, label='S12 Phase', linewidth=2)
plt.xlabel('Frequency (GHz)')
plt.ylabel('Phase (degrees)')
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

# Print some network information
print("Network Summary:")
print(f"Name: {ntwk.name}")
print(f"Frequency range: {ntwk.f[0]/1e9:.2f} - {ntwk.f[-1]/1e9:.2f} GHz")
print(f"Number of points: {ntwk.f.size}")

# Group Delay Calculation
freq = ntwk.f
phase_s21 = np.unwrap(np.angle(ntwk.s[:,1,0]))
phase_s12 = np.unwrap(np.angle(ntwk.s[:,0,1]))
group_delay_s21 = -np.gradient(phase_s21, freq) / (2 * np.pi)
group_delay_s12 = -np.gradient(phase_s12, freq) / (2 * np.pi)

plt.figure(figsize=(10, 6))
plt.plot(freq / 1e9, group_delay_s21 * 1e9, linewidth=2, label='Group Delay (S21)')
plt.plot(freq / 1e9, group_delay_s12 * 1e9, linewidth=2, label='Group Delay (S12)')
plt.xlabel('Frequency (GHz)')
plt.ylabel('Group Delay (ns)')
plt.title(f'Group Delay of {ntwk.name or "Network"}')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Time-Domain Response via Inverse Fourier Transform (IFT)
s21_freq = ntwk.s[:,1,0]
s12_freq = ntwk.s[:,0,1]
time_response_s21 = np.fft.ifft(s21_freq)
time_response_s12 = np.fft.ifft(s12_freq)
time_axis = np.fft.fftfreq(len(freq), d=(freq[1] - freq[0]))

plt.figure(figsize=(10, 6))
plt.plot(time_axis * 1e9, np.abs(time_response_s21), linewidth=2, label='IFT of S21')
plt.plot(time_axis * 1e9, np.abs(time_response_s12), linewidth=2, label='IFT of S12')
plt.xlim(0, 100)
plt.xlabel('Time (ns)')
plt.ylabel('Magnitude')
plt.title(f'Time-Domain Response of {ntwk.name or "Network"}')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()



import numpy as np
import pandas as pd

def convert_s2p_to_complex(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()

    data = []
    metadata = []

    for line in lines:
        if line.startswith('#') or line.startswith('!') or line.strip() == '':
            metadata.append(line)  # Store metadata/header
        else:
            values = list(map(float, line.split()))
            freq = values[0]  # Frequency column
            s_params = [complex(values[i], values[i+1]) for i in range(1, len(values), 2)]  # Convert to complex
            data.append([freq] + s_params)

    return metadata, np.array(data)

def save_to_excel(data, output_filename):
    # Extract frequency and S-parameters (real & imaginary separately)
    freq = data[:, 0]  # First column is frequency
    s11, s12, s21, s22 = data[:, 1], data[:, 2], data[:, 3], data[:, 4]

    df = pd.DataFrame({
        'Frequency (Hz)': freq,
        'S11 Real': s11.real, 'S11 Imag': s11.imag,
        'S12 Real': s12.real, 'S12 Imag': s12.imag,
        'S21 Real': s21.real, 'S21 Imag': s21.imag,
        'S22 Real': s22.real, 'S22 Imag': s22.imag
    })

    # Save to Excel
    df.to_excel(output_filename, index=False, engine='openpyxl')

# Example usage:
filename = "gfdgsgf.s2p"  # Replace with actual file
output_xlsx = "converted_s2p.xlsx"

metadata, s_params = convert_s2p_to_complex(filename)
save_to_excel(s_params, output_xlsx)

print(f"Converted S-parameters saved to {output_xlsx}")

"""# New Section"""

!pip install scikit-rf